### ISSUE TITLE
Internal Compiler Error (when building)

### ISSUE THREAD

**Issue by muneeb-ali** [namecoinq/namecoinq#2]
Hi, 

I'm getting an "internal compiler error" when building ver vQ.3.72. Here is the output:

```
standard input}: Assembler messages:
{standard input}:22008: Warning: end of file not at end of a line; newline inserted
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [build/util.o] Error 4
ubuntu@vm:~/namecoinq$ 
```

I've seen the same bug on both Fedora 19 and Ubuntu 13 and my systems can successfully compile Bitcoin (e.g., ver 0.8.3)

**Comment by muneeb-ali** [comment]
The above error occurs on 64-bit distributions. I was able to compile vQ.3.72 on a 32-bit Ubuntu 13.

**Comment by Pagel1928** [comment]
Hey, often you will see this error if you run out of memory and the OOM killer kills the compiler process, perhaps that is the issue?

**Comment by muneeb-ali** [comment]
Yes, compiling on a VM with more memory does seem to work. Not sure if that was the real cause of the error though.
